<?php


namespace app\components;



use app\models\Activity;
use yii\base\Component;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

class ActivityComponent extends Component
{
    public $modelClass;

    public function init()
    {
        parent::init();

        // TODO: Change the autogenerated stub
    }

    public function getModel()
    {
        return new $this->modelClass;
    }

    public function addActivity(Activity $activity) :bool
    {
        $activity->files = UploadedFile::getInstances($activity, 'files');
        $fileSaver = \Yii::createObject(['class' => FileSaverComponent::class]);
        if ($activity->validate()) {
            foreach ($activity->files as &$file) {
                $file = $fileSaver->saveFile($file);
//                $file = $this->saveFile($file);
                if (!$file) {
                    return false;
                }
            }
            return true;
        }
        return false;
    }



}