<?php


namespace app\components;



use phpDocumentor\Reflection\Types\Boolean;
use yii\base\Component;

class ActivityComponent extends Component
{
    public $modelClass;

    public function init()
    {
        parent::init();

        // TODO: Change the autogenerated stub
    }

    public function getModel()
    {
        return new $this->modelClass;
    }

    public function addActivity(Activity $activity) :Boolean
    {
        if ($activity->validate()) {
            return true;
        }

        return false;
    }

}