<?php


namespace app\base;

use yii\web\Controller;
use yii\web\HttpException;

class BaseController extends Controller
{
    public $previousUrl = '/';
    public function beforeAction($action)
    {
//        if (\Yii::$app->user->isGuest){
//            throw new HttpException(401,'NotAuth');
//        }
        $this->previousUrl = \Yii::$app->request->getPathInfo();
        $previousUrl = \Yii::$app->session->get('previousUrl');
        \Yii::$app->params['previousUrl'] = $previousUrl;
        return parent::beforeAction($action);
    }
    public function afterAction($action, $result)
    {
//        \Yii::$app->params['previousUrl'] = $this->previousUrl;
        \Yii::$app->session->set('previousUrl',$this->previousUrl);

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}